### ISSUE TITLE
Order of fields in general template

### ISSUE THREAD

**Issue by JuliaSprenger** [INT-NIT/DigLabTools#27]
During the discussion of the covoprim project the suggestion came up to reorder the general fields of the survey according to logical groups, i.e. have experiment related data grouped  and animal specific data grouped...

The current order of fields is

- Ethical Protocol Identifier
- User
- Session date
- Experiment Name
- Subject GUID
- Session Number
- Modality
- Stimulation?
- Weight
- Experiment (comment)
- Setup/Recording (comment)
- Subject Behaviour (comment)
- Electrophysiology Data quality
- Incomplete session?
- Subject Behaviour
- Data recorded after last trials?
- Fluid (reward)
- Fluid (additional)
- Other reward
- Special event (alarm, fight, perturbation,...)
- Time of the special event

The current suggestion for this reordering according to groups  would be 

General metadata
- Ethical Protocol Identifier
- User
- Session date
- Experiment Name
- Experiment (comment)
- Subject GUID
- Session Number
- Modality

Recording
- Stimulation?
- Data recorded after last trials?
- Setup/Recording (comment)
- Electrophysiology Data quality
- Incomplete session?
- Special event (alarm, fight, perturbation,...)
- Time of the special event

Subject
- Subject Behaviour
- Subject Behaviour (comment)
- Weight
- Fluid (reward)
- Fluid (additional)
- Other reward

@fredbarthelemy I know that the original order was intended to follow the order in which the metadata are accumulated during the experiment, but this order might differ from experiment to experiment. So maybe a logical grouping would make more sense for a general template?

**Comment by fredbarthelemy** [comment]
Just to precise a bit my short response.

I adapted my matlab script for the generation of metadata using the new RedCap standards for date and session number and it works just fine.

But for the moment, these changes only take care of the output format of the lab book and not its content. I expect no problem for everything that would affect the page organization if there is no modifications of the variable names in the csv report. My script is indeed independent from variable order and decode the csv file header itself to determine where to find the metadata. For this reason, a change in the organization of the fields to follow a thematic order rather than a chronological order should be fine. That's why I basically answered that I didn't really care and to ask the users about it ;)

I think there will be no problem for the reward fluid type, because it's just an extra metadata (I suppose). In this case I could easily add the extraction of this metadata to the list.

The only uncertain point would be the multiplicity of "special events" if the variable "special_event" and "special_event_time" are renamed for example in "special_event_1" and "special_event_time_1".

**Comment by JuliaSprenger** [comment]
Ok, I merged the reordering of the fields in the survey view. About the special events, I think it makes sense to allow for multiple timepoints of those. Concerting the space in the survey there's no difference as the additional special_event fields will only become visible once one special_event has been filled. So from the user perspective it's the same experience in case no special events are registered.

**Comment by fredbarthelemy** [comment]
Hello, I just have a quick comment on special event time and on time in general. I failed to find in diglab the possibility to actually indicate time in specific format like mm:ss for example. Do you know if there is a way to do it? It could be useful in situations when the time correspond to the duration since the begining of the experiment.

**Comment by JuliaSprenger** [comment]
Hi Fred, RedCap supports a set of time related data types, but unfortunately none of them matches mm:ss. What we have available is
- time (hh:mm)
- date (D-M-Y)
- datetime (D-M-Y H:M)
- datetime with seconds ((D-M-Y H:M:S)
So if you want to explicitely capture minutes and seconds then we should maybe handle these as two separate fields.

**Comment by JuliaSprenger** [comment]
I will close this as the original issue is adressed via #30. @fredbarthelemy. If you need more discussion on the time format please start another issue.
